/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import javax.swing.JLabel;
import cordinator.Cordinator;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author dakik
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelIme = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jButtonIzmenaProfesor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemUnosKupca = new javax.swing.JMenuItem();
        jMenuItemPrikazKupaca = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemUnosKolaca = new javax.swing.JMenuItem();
        jMenuItemPrikazKolaca = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemUnosSmene = new javax.swing.JMenuItem();
        jMenuItemPrikazSmena = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemUnosRacuna = new javax.swing.JMenuItem();
        jMenuItemPrikazRacuna = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trenutno prijavljeni profesor"));

        jLabel1.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("Email:");

        jLabelIme.setText("jLabel2");

        jLabelPrezime.setText("jLabel2");

        jLabelEmail.setText("jLabel2");

        jButtonIzmenaProfesor.setText("Izmena kredencijala");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelIme))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPrezime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addComponent(jButtonIzmenaProfesor)
                        .addGap(90, 90, 90))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelIme))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelPrezime)
                    .addComponent(jButtonIzmenaProfesor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelEmail))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jMenu1.setText("Ucenik");

        jMenuItemUnosKupca.setText("Unos učenika");
        jMenuItemUnosKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosKupcaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUnosKupca);

        jMenuItemPrikazKupaca.setText("Prikaz svih učenika");
        jMenuItemPrikazKupaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazKupacaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPrikazKupaca);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Nastavna jedinica");

        jMenuItemUnosKolaca.setText("Unos nastavnih jedinica");
        jMenuItemUnosKolaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosKolacaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemUnosKolaca);

        jMenuItemPrikazKolaca.setText("Prikaz svih nastavnih jedinica");
        jMenuItemPrikazKolaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazKolacaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPrikazKolaca);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Kvalifikacija");

        jMenuItemUnosSmene.setText("Unos kvalifikacije");
        jMenuItemUnosSmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosSmeneActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemUnosSmene);

        jMenuItemPrikazSmena.setText("Prikaz svih kvalifikacija");
        jMenuItemPrikazSmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazSmenaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemPrikazSmena);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Evidencija Kursa");

        jMenuItemUnosRacuna.setText("Unos nove evidencije");
        jMenuItemUnosRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosRacunaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemUnosRacuna);

        jMenuItemPrikazRacuna.setText("Prikaz svih evidencija");
        jMenuItemPrikazRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazRacunaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemPrikazRacuna);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Trenutno prijavljeni profesor\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUnosKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosKupcaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriDodajUcenikFormu();
    }//GEN-LAST:event_jMenuItemUnosKupcaActionPerformed

    private void jMenuItemUnosKolacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosKolacaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriDodajNastavnuJedinicuFormu();
    }//GEN-LAST:event_jMenuItemUnosKolacaActionPerformed

    private void jMenuItemPrikazKolacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazKolacaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikazNastavnaJedinicaFormu();
    }//GEN-LAST:event_jMenuItemPrikazKolacaActionPerformed

    private void jMenuItemUnosSmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosSmeneActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriDodajKvalifikacijuFormu();
    }//GEN-LAST:event_jMenuItemUnosSmeneActionPerformed

    private void jMenuItemPrikazKupacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazKupacaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikazUcenikaFormu();
    }//GEN-LAST:event_jMenuItemPrikazKupacaActionPerformed

    private void jMenuItemUnosRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosRacunaActionPerformed
        try {
            // TODO add your handling code here:
            Cordinator.getInstance().otvoriDodajEKFormu();
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemUnosRacunaActionPerformed

    private void jMenuItemPrikazSmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazSmenaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikaziKvalifikacijeFormu();
    }//GEN-LAST:event_jMenuItemPrikazSmenaActionPerformed

    private void jMenuItemPrikazRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazRacunaActionPerformed
        // TODO add your handling code here:
        Cordinator.getInstance().otvoriPrikazEKFormu();
    }//GEN-LAST:event_jMenuItemPrikazRacunaActionPerformed

    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmenaProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemPrikazKolaca;
    private javax.swing.JMenuItem jMenuItemPrikazKupaca;
    private javax.swing.JMenuItem jMenuItemPrikazRacuna;
    private javax.swing.JMenuItem jMenuItemPrikazSmena;
    private javax.swing.JMenuItem jMenuItemUnosKolaca;
    private javax.swing.JMenuItem jMenuItemUnosKupca;
    private javax.swing.JMenuItem jMenuItemUnosRacuna;
    private javax.swing.JMenuItem jMenuItemUnosSmene;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables



    public JLabel getjLabelPrezime() {
        return jLabelPrezime;
    }

    public JLabel getjLabelIme() {
        return jLabelIme;
    }

    public JLabel getjLabelEmail() {
        return jLabelEmail;
    }

    public JButton getjButtonIzmenaProfesor() {
        return jButtonIzmenaProfesor;
    }

    public void addBtnIzmeniProfilActionListener(ActionListener actionListener) {
        jButtonIzmenaProfesor.addActionListener(actionListener);
    }
    
    
}
